//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InternationalCookies_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CookieOrder
    {
        public int OrderID { get; set; }
        public Nullable<int> StoreID { get; set; }
        public Nullable<int> CookiesRequired { get; set; }

        public Nullable<DateTime> OrderedDate { get; set; }


        public StoreDetail StoreDetail { get; set; }
    }
}
